name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop, fix/*, feat/* ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@main
        timeout-minutes: 5

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        timeout-minutes: 5
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          reporter: github-pr-review
          level: 'warning'
          android: true
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Cache Gradle Packages
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ github.head_ref }}-${{ github.base_ref }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-${{ github.head_ref }}-${{ github.base_ref }}-
          ${{ runner.os }}-gradle-${{ github.head_ref }}
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
